#!/bin/sh
set -e

PACKAGE_NAME="rudder-server-root"
LOG_FILE="/var/log/rudder/install/${PACKAGE_NAME}.log"

CFRUDDER_FIRST_INSTALL="$1"

if [ -z "$1" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL>"
  echo " This should only be called from a package preinstall command"
  exit 1
fi

echo "`date` - Starting ${PACKAGE_NAME} pre installation script" >> ${LOG_FILE}

## WARNING: This script is a copy of a part of the rudder-agent preinst

if [ ${CFRUDDER_FIRST_INSTALL} -ne 1 ]
then
  mkdir -p /var/rudder/tmp

  if [ -f /etc/init.d/rudder ]
  then
    # If old rudder service is here and enabled
    if type chkconfig > /dev/null
    then 
      if chkconfig --list rudder 2>&1 | grep -q -e 3:on -e B:on
      then
        touch /var/rudder/tmp/migration-rudder-service-enabled
      fi
    fi

    if test /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S??rudder
    then
      touch /var/rudder/tmp/migration-rudder-service-enabled
    fi
  fi
fi
