#!/bin/bash
set -e

LOG_FILE="/var/log/rudder/install/rudder-server-root-$(date +%Y%m%d%H%M%S).log"
RUDDER_DIR="/opt/rudder/"

CFRUDDER_FIRST_INSTALL="$1"
if [ -z "$1" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL>"
  echo " This should only be called from a package postinstall command"
  exit 1
fi

echo "`date` - Starting rudder-server-root post installation script" >> ${LOG_FILE}

systemctl daemon-reload
systemctl enable rudder-server >> ${LOG_FILE}

# We need it to be able to open big mdb memory-mapped databases
ulimit -v unlimited

echo "$(date) - Ending rudder-server-root post installation script" >> ${LOG_FILE}
