#!/bin/bash
set -e

PACKAGE_NAME="rudder-server-root"
LOG_FILE="/var/log/rudder/install/${PACKAGE_NAME}.log"
RUDDER_DIR="/opt/rudder/"

CFRUDDER_FIRST_INSTALL="$1"
if [ -z "$1" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL>"
  echo " This should only be called from a package postinstall command"
  exit 1
fi

echo "`date` - Starting rudder-server-root post installation script" >> ${LOG_FILE}

systemctl daemon-reload

# Enable at first install
if [ ${CFRUDDER_FIRST_INSTALL} -eq 1 ]
then
  if type chkconfig > /dev/null 2>&1
  then
    chkconfig --add rudder-server
    chkconfig rudder-server on
  fi

  if type update-rc.d > /dev/null 2>&1
  then
    update-rc.d rudder-server defaults
  fi
else
# Upgrade flag is here
  if [ -f /var/rudder/tmp/migration-rudder-service-enabled-server ]
  then
    if type chkconfig > /dev/null 2>&1
    then
      chkconfig --add rudder-server
      chkconfig rudder-server on
    fi

    if type update-rc.d > /dev/null 2>&1
    then
      update-rc.d rudder-server defaults
    fi
  fi
fi

# Clean flag
rm -f /var/rudder/tmp/migration-rudder-service-enabled-server

# This package is only installed by the root server
# then we can set UUID to 'root' serenly
echo 'root' > ${RUDDER_DIR}/etc/uuid.hive

# We need it to be able to open big mdb memory-mapped databases
ulimit -v unlimited

# Check if Rudder LDAP has already been initialize previously
LDAPCHK=`/opt/rudder/sbin/slapcat  | grep "^dn: " | wc -l`
if [ $LDAPCHK -eq 0 ]; then
  echo "************************************************************"
  echo "Rudder is now installed but not configured."
  echo "Please run /opt/rudder/bin/rudder-init"
  echo "************************************************************"
fi

