#!/bin/sh
# preinst script for rudder-webapp
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install)
      dpkg-divert --add --rename --package rudder-server /opt/rudder/etc/rudder-apache-webapp-common.conf
      dpkg-divert --add --rename --package rudder-server /opt/rudder/etc/rudder-apache-webapp-nossl.conf
      dpkg-divert --add --rename --package rudder-server /opt/rudder/etc/rudder-apache-webapp-ssl.conf
      dpkg-divert --add --rename --package rudder-server /opt/rudder/etc/rudder-jetty.conf

      mkdir -p /opt/rudder/etc
      echo 'root' > /opt/rudder/etc/uuid.hive
      mkdir -p /var/rudder/cfengine-community/
      echo "127.0.0.1" > /var/rudder/cfengine-community/policy_server.dat
      # make sure keys and certificate are the server ones
      [ -x /opt/rudder/bin/rudder ] && /opt/rudder/bin/rudder agent check -f -s keys
    ;;

    upgrade)

      LOG_FILE="/var/log/rudder/install/rudder-server-$(date +%Y%m%d).log"
      echo "`date` - Starting rudder-server pre installation script" >> ${LOG_FILE}
      # When upgrading OpenLDAP, we may need to dump the database
      # so that it can be restored from LDIF in case the new
      # package uses a different version of BerkeleyDB (libdb)
      TIMESTAMP=`date +%Y%m%d%H%M%S`
      # Ensure backup folder exist
      mkdir -p /var/rudder/ldap/backup/
      chmod 750 /var/rudder/ldap/backup/

      # We need it to be able to open big mdb memory-mapped databases
      ulimit -v unlimited

      [ -x /opt/rudder/sbin/slapcat ] && /opt/rudder/sbin/slapcat -b "cn=rudder-configuration" -l /var/rudder/ldap/backup/openldap-data-pre-upgrade-${TIMESTAMP}.ldif

      # Both files below are read back to drive a privileged action, so they stay in root-owned
      # /var/rudder/tmp: the statuses decide which jars the webapp loads, the ACL dump is fed back
      # to setfacl.
      RUDDER_TMP="/var/rudder/tmp"
      PLUGIN_STATUS_FILE="${RUDDER_TMP}/upgrade-plugins-status-backup"
      PLUGIN_STATUS_LOG="${RUDDER_TMP}/upgrade-plugins-save-log"
      HOOKS_ACL_FILE="${RUDDER_TMP}/upgrade-hooks-acl"
      LEGACY_STATUS_FILE="/tmp/rudder-plugins-upgrade"
      mkdir -p "${RUDDER_TMP}"

      # Here we write the list of plugins states. Two versions:
      # - pre-9.0.9/9.1.4 were the list is written directly into /tmp/rudder-plugins-upgrade
      #   with a message on stderr "Plugins statuses saved in ..."
      # - later versions, were the status is written into stdout
      #
      # As the preinst runs on the old binary we need to handle both until 9.1 is EOL.
      #
      # To do so we run the save command and redirect stdout and stderr to files.
      # Then we check the stderr for the old message:
      # - If the old message is there and the file in /tmp looks ok (not a symlink
      #   owned by root) we use its content
      # - Else we use the output of the command directly.
      rm -f "${PLUGIN_STATUS_FILE}" "${LEGACY_STATUS_FILE}"
      (umask 077; rudder package enable --save > "${PLUGIN_STATUS_FILE}" 2> "${PLUGIN_STATUS_LOG}")
      OLD_BINARY_STATUS_FILE=$(sed -n 's/.*Plugins statuses saved in //p' \
        "${PLUGIN_STATUS_LOG}" | tail -n 1)
      if [ -n "${OLD_BINARY_STATUS_FILE}" ] && [ -f "${OLD_BINARY_STATUS_FILE}" ] \
         && [ ! -L "${OLD_BINARY_STATUS_FILE}" ] && [ -O "${OLD_BINARY_STATUS_FILE}" ]; then
        cat "${OLD_BINARY_STATUS_FILE}" > "${PLUGIN_STATUS_FILE}"
      fi
      rm -f "${PLUGIN_STATUS_LOG}" "${LEGACY_STATUS_FILE}"

      getfacl --absolute-names --recursive /opt/rudder/etc/hooks.d/ > "${HOOKS_ACL_FILE}"
      chmod 600 "${HOOKS_ACL_FILE}"

      echo "********************************************************************************"
      echo "INFO: dpkg may ask you if you want to replace rudder-web.properties or          "
      echo "INFO: slapd.conf with the maintainer version.                                   "
      echo "INFO:                                                                           "
      echo "INFO: If you accept, please keep in mind that you will lose any manual          "
      echo "INFO: modifications in this file, like batchs configuration, or LDAP            "
      echo "INFO: authentication. It will also reset passwords to default values and break  "
      echo "INFO: upgrade scripts.                                                          "
      echo "INFO:                                                                           "
      echo "INFO: We strongly advise you to respond NO to this question                     "
      echo "INFO: ('keep your currently-installed version'). Rudder's upgrade script will   "
      echo "INFO: take care of upgrading these file automatically.                          "
      echo "INFO:                                                                           "
      echo "********************************************************************************"
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
