#!/bin/sh
# postinst script for rudder-inventory-ldap
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Variables
VAR_RUDDER="/var/rudder"
PT_DIR="${VAR_RUDDER}/configuration-repository/policy-templaltes"

case "$1" in
    configure)
		invoke-rc.d rsyslog reload
  /etc/init.d/apache2 stop
  a2dissite default
  a2enmod dav_fs
  a2enmod rewrite
  a2enmod proxy_http
  # Add right to apache user to access /var/rudder/inventories/incoming
  chmod 751 /var/rudder/inventories
  chown root:www-data /var/rudder/inventories/incoming
  chmod 2770 /var/rudder/inventories/incoming
  chmod 755 -R /opt/rudder/share/tools
  a2ensite rudder-default
  htpasswd -bc /opt/rudder/etc/htpasswd-webdav rudder rudder
  /etc/init.d/apache2 start

  # Migrate from 2.3.0 format policy-template store: /var/rudder/policy-templates
  if [ -d /var/rudder/policy-templates -a ! -d /var/rudder/configuration-repository ]; then
      echo "***** WARNING *****"
      echo "The policy template store for Rudder has changed. It will be"
      echo "automatically moved from /var/rudder/policy-templates to"
      echo "/var/rudder/configuration-repository/policy-templates."

	  cd /var/rudder/policy-templates && git add . && git add -u && git commit -am "Committing all pending policy template changes for automatic migration of the policy template store to /var/rudder/configuration-repository/policy-templates" || true

	  mkdir -p /var/rudder/configuration-repository
	  mv /var/rudder/policy-templates/.git /var/rudder/configuration-repository/
	  mv /var/rudder/policy-templates /var/rudder/configuration-repository/
	  cd /var/rudder/configuration-repository/ && git add -u
	  cd /var/rudder/configuration-repository/ && git add policy-templates/
	  cd /var/rudder/configuration-repository/ && git commit -m "Move policy-templates into configuration-repository directory"

	  sed -i 's%^rudder.dir.policyPackages *= */var/rudder/policy-templates/\?$%rudder.dir.policyPackages=/var/rudder/configuration-repository/policy-templates%' /opt/rudder/etc/rudder-web.properties
	  echo "rudder.dir.gitRoot=/var/rudder/configuration-repository" >> /opt/rudder/etc/rudder-web.properties

	  echo "Automatic migration to /var/rudder/configuration-repository/policy-templates done."
  fi

  # Create and populate policy-template store
  if [ ! -d /var/rudder/configuration-repository ]; then
	  mkdir -p /var/rudder/configuration-repository
	  mkdir -p /var/rudder/configuration-repository/shared-files
	  cp -a /opt/rudder/share/policy-templates /var/rudder/configuration-repository/
  fi


  # Check default folder for shared-files exists
  if [ ! -d /var/rudder/configuration-repository/shared-files ]; then
    echo "/var/rudder/configuration-repository/shared-files doesn't exist !"
    mkdir -p /var/rudder/configuration-repository/shared-files
    # If this folder doesn't contain files, git won't commit it
    # To simplify usage, we want that the user can add files simply
    # So when he will add files into shared-files they will appears in git status
    # So we force git to add the folder
    CONTENT=`ls /var/rudder/configuration-repository/shared-files/ | wc -l`
    if [ ${CONTENT} -eq 0 ]; then
        touch /var/rudder/configuration-repository/shared-files/.placeholder
        # Check if git init has been made, if not rudder will do it so we don't have to
        if [ -d /var/rudder/configuration-repository/.git ]; then
            cd /var/rudder/configuration-repository/ && git add shared-files/
            cd /var/rudder/configuration-repository/ && git commit -m "Add default shared-files directory" shared-files/
        fi
	fi
		echo "/var/rudder/configuration-repository/shared-files created"
	fi
	# Check shared-files folder is set in rudder-web.properties
	ATTRIBUTESET=`grep "^rudder.dir.shared.files.folder" /opt/rudder/etc/rudder-web.properties | wc -l`
	if [ ${ATTRIBUTESET} -gt 0 ]; then
		#Idea: when we will be asking for shared files folder path, sed will be used here
		echo "rudder.dir.shared.files.folder attribute already set in rudder-web.properties"
	else
		echo "rudder.dir.shared.files.folder=/var/rudder/configuration-repository/shared-files" >> /opt/rudder/etc/rudder-web.properties
		echo "rudder.dir.shared.files.folder attribute set in rudder-web.properties"
	fi

	# Migration of PT 'Set the permissions of files' (Ensure that all actions below won't happen if migration has already made)
	if [ ! -f ${PT_DIR}/fileConfiguration/fileSecurity/filesPermissions/1.0/policy.xml ]; then
	## Create right folder if it doesn't exist
		if [ ! -d ${PT_DIR}/fileConfiguration/fileSecurity/ ]; then
			mkdir -p "${PT_DIR}/fileConfiguration/fileSecurity"
			echo "${PT_DIR}/fileConfiguration/fileSecurity has been created"
		else
			echo "${PT_DIR}/fileConfiguration/fileSecurity already exists"
		fi

		if [ -d ${PT_DIR}/fileConfiguration/security/ ]; then
	## Check that filePermissions.st located in fileConfiguration/security/ is not duplicated and in the right folder
			if [ -d ${PT_DIR}/fileConfiguration/security/filesPermissions/ ]; then
				echo "The Policy Template 'Set the permissions of files' is not correctly located"
				cd /var/rudder/configuration-repository/ && git mv policy-templates/fileConfiguration/security/filesPermissions/ policy-templates/fileConfiguration/fileSecurity/
				cd /var/rudder/configuration-repository/ && git commit -m "Correct Policy Template 'Set the permissions of files' location" policy-templates/fileConfiguration/security/filesPermissions/
				echo "The location of the Policy Template 'Set the permissions of files' is now correct"
			fi
	## Check that a category exist on fileSecurity folder, if not move from security folder
			if [ ! -f ${PT_DIR}/fileConfiguration/fileSecurity/category.xml ]; then
				echo "${PT_DIR}/fileConfiguration/fileSecurity/category.xml is missing"
				if [ -f ${PT_DIR}/fileConfiguration/security/category.xml ]; then
					cd /var/rudder/configuration-repository/ && git mv policy-templates/fileConfiguration/security/category.xml policy-templates/fileConfiguration/fileSecurity/ && git commit -m "Move category description from fileConfiguration/security/ to fileConfiguration/fileSecurity/"
					echo "${PT_DIR}/fileConfiguration/security/category.xml has been moved to ${PT_DIR}/fileConfiguration/fileSecurity/category.xml"
				else
					echo "can't find ${PT_DIR}/fileConfiguration/security/category.xml"
					exit 1
				fi
			fi
	## Check that no others directories are located in fileConfiguration/security/
			NBR_DIR=`find ${PT_DIR}/fileConfiguration/security/ -mindepth 1 -maxdepth 1 -type d | wc -l`
			if [ ${NBR_DIR} -ne 0 ]; then
				echo "Some folder remains in the folder /var/rudder/configuration-repository/policy-templates/fileConfiguration/security/"
				cd /var/rudder/configuration-repository/ && find policy-templates/fileConfiguration/security/ -mindepth 1 -maxdepth 1 -type d | xargs -I SRCFOLDER git mv SRCFOLDER policy-templates/fileConfiguration/fileSecurity/
				cd /var/rudder/configuration-repository/ && git commit -m "Move all remnant folder from fileConfiguration/security/ to fileConfiguration/fileSecurity/" policy-templates/fileConfiguration/fileSecurity/
				echo "All the folder from ${PT_DIR}/fileConfiguration/security/ are now moved to ${PT_DIR}/fileConfiguration/fileSecurity/"
			fi
	## Remove the folder which should contain no more files or folder
		rm -rf policy-templates/fileConfiguration/security/ # Not using git since it can't manage folder without file
		echo  "${PT_DIR}/fileConfiguration/security/ has been removed"
		fi
	fi

  # Restart the webapp
  echo "Restarting Rudder webapp and inventory-endpoint"
  /etc/init.d/jetty restart

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
