#!/bin/bash

set -xe

# relink all binaries from a given directory to use absolute library path for rudder embedded libraries
dir="$1"
if [ "${dir}" = "" ]
then
  echo "Usage $0 <rudder directory>"
  exit 1
fi

# point real /opt/rudder/lib to $dir
if [ -e "/opt/ruder/lib" ]
then
  echo "Rudder must no be installed on this machine"
  exit 1
fi
mkdir -p /opt/rudder
ln -s "${dir}/lib" /opt/rudder/lib

# function to relink executable files (binaries and .so)
relink() {
  mode="$1"
  base="$2"
  rudder_libpath="/opt/rudder/lib:/usr/lib:/lib"

  # list executable files
  if [ "${mode}" = "bin" ]; then
    files=$(for i in ${base}/*; do file $i; done | grep "executable" | sed 's/:.*//')
  elif [ "${mode}" = "so" ]; then
    files=$(for i in ${base}/*.so.*; do file $i; done | grep "executable" | sed 's/:.*//')
  fi

  # keep files with rudder dependencies
  executables=$(for f in ${files}
  do
    if LIBPATH="${rudder_libpath}" ldd "${f}" | grep -v "${f}" | grep ${dir}/lib > /dev/null
    then
      echo "${f}"
    fi
  done)
  
  # relink
  for f in ${executables}
  do
    echo $f
    dest=$(mktemp)
    # extract rudder dependencies with full path to final destination
    path=$(LIBPATH="${rudder_libpath}" ldd "${f}" | grep " /opt/rudder/lib" | sed 's/(.*//' | sort -u)
    # extract other dependencies with library name
    lib=$(LIBPATH="${rudder_libpath}" ldd "${f}" | grep -e " /usr/lib/lib" -e " /lib/lib" | sed 's|.*/lib/lib\([^.]*\).*|-l\1|' | sort -u)
    # relink with static paths and proper libpath (just in case)
    if [ "${mode}" = "bin" ]; then
      ld -bipath -bsvr4 -blibpath:${rudder_libpath} "${f}" ${path} ${lib} -o "${dest}" && mv "${dest}" "${f}"
    elif [ "${mode}" = "so" ]; then
      ld -bipath -bsvr4 -blibpath:${rudder_libpath} -bnoentry -bstatic "${f}" -bshared ${path} ${lib} -o "${dest}" && mv "${dest}" "${f}"
    fi
  done
}

# 1- relink binaries
relink "bin" "${dir}/bin"

# 2- relink .so libraries
relink "so" "${dir}/lib"

# 3- relink .a libraries
# list only libraries that contain .so files
archive_files=$(for i in ${dir}/lib/*.a; do file $i; done | grep "archive" | sed 's/:.*//')
files=$(for i in ${archive_files}; do dump -H $i; done | grep '\[.*\.so.*\]' | sed 's/\[.*//')
# extract so files from archives
tmpdir=$(mktemp -d)
cd "${tmpdir}"
for f in ${files}
do
  ar x "${f}"
done
# relink .so from within .a
relink "so" "${tmpdir}"
# put back .so to their place
for f in ${files}
do
  so=$(ar t "${f}")
  ar r "${f}" "${so}"
done
rm -rf "${tmpdir}"

rm /opt/rudder/lib
