## This file contains the local agent settings, mainly related to agent-server communication.

# Overrides/replaces the policy server host configured in policy_server.dat
# There is usually no need to set it.
#
#server=

# Port to use for HTTPS communication with the server
#
#https_port=443

# Proxy for HTTPS communication with the server
#
#https_proxy=

# Enforce using only the HTTPS protocol, disable the communications over port 5309
# and the `rudder-cf-serverd` service.
#
#https_only=false

# Use standard PKI-based certificate validation instead of the built-in pinning mechanism.
# WARNING: It requires specific configuration before being enabled, see:
# https://docs.rudder.io/reference/current/administration/security.html#_using_https_port_443_only_between_rudder_server_and_nodes
#
#cert_validation=false

# Backend to use for the inventory, can be:
# - "fusion": the default backend, providing the full inventory
# - "module": a lighter experimental backend, providing a small subset of the inventory
#
#inventory=fusion
