#!/bin/sh
#####################################################################################
# Copyright 2013 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

set -e

BACKUP_DIR=/var/backups/rudder/

check_and_fix_cfengine_processes() {

# Default variables for CFEngine binaries and disable files
CFE_DIR=/var/rudder/cfengine-community
CFE_BIN_DIR=${CFE_DIR}/bin
CFE_DISABLE_FILE=/opt/rudder/etc/disable-agent

# Detect the correct ps tool to use
# Supported tools are ps, vzps, and the rudder supplied vzps.py
PS=ps
VZPS=/bin/vzps
RUDDERPS=/opt/rudder/bin/vzps.py

# Detect if we are a VZ host
if [ -e "/proc/bc/0" ]; then
  # Detect if vzps is present
  if [ -e ${VZPS} ]; then
    PS="${VZPS} -E 0"
  else
    PS="${RUDDERPS} -E 0"
  fi
fi

LAST_UPDATE_FILE=${CFE_DIR}/last_successful_inputs_update

# List the CFEngine processes running
CF_PROCESS_RUNNING=`${PS} -efww | grep -E "${CFE_BIN_DIR}/(cf-execd|cf-agent)" | grep -v grep | cat`
# Count the number of processes running, filtering empty lines
NB_CF_PROCESS_RUNNING=`echo "${CF_PROCESS_RUNNING}" | grep -v ^$ | wc -l`

# If no disable file AND no process of CFEngine from Rudder, then relaunch cf-agent with a failsafe first
# But this is applied only on servers or nodes already initialized (policy server set)
if [ ! -e ${CFE_DISABLE_FILE} -a ${NB_CF_PROCESS_RUNNING} -eq 0 -a -f ${CFE_DIR}/policy_server.dat ]; then
  echo -n "WARNING: No disable file detected and no CFEngine process neither. Relaunching CFEngine processes..."
  ${CFE_BIN_DIR}/cf-agent -f failsafe.cf >/dev/null 2>&1
  ${CFE_BIN_DIR}/cf-agent >/dev/null 2>&1
  echo " Done"
fi

# Check for the age of the last update file
# if it is older than 10 minutes, we need to kill the lock file on tcdb database
if [ ! -e ${LAST_UPDATE_FILE} ]; then
  # The file ${LAST_UPDATE_FILE} is not yet present, this node is probably 
  # not accepted yet. Do nothing
  :
elif test `find ${LAST_UPDATE_FILE} -mmin +10`; then
  echo -n "WARNING: The file ${LAST_UPDATE_FILE} is older than 10 minutes, the agent is probably stuck. Purging the TokyoCabinet lock file..."
  rm -f ${CFE_DIR}/state/cf_lock.tcdb.lock
  echo " Done";
fi


# Check for anomalous number of CFEngine processes
# If there are more than 8 agent/executor processes, we should kill them, and purge the tcdb database
if [ ${NB_CF_PROCESS_RUNNING} -gt 8 ]; then
  echo -n "WARNING: Too many instance of CFEngine processes running. Killing them, and purging the TokyoCabinet database..."
  echo "${CF_PROCESS_RUNNING}" | awk 'BEGIN { OFS=" "} {print $2 }' | xargs kill -9 || true
  /etc/init.d/rudder-agent forcestop || true
  rm -f ${CFE_DIR}/state/cf_lock.tcdb
  rm -f ${CFE_DIR}/state/cf_lock.tcdb.lock
  echo " Done"
fi
}

check_and_fix_rudder_uuid() {

# Default variables about UUID file and its backups
UUID_FILE=/opt/rudder/etc/uuid.hive
LATEST_BACKUPED_UUID=""

# Generate a UUID if we don't have one yet
if [ ! -e ${UUID_FILE} ]; then
  if [ -d ${BACKUP_DIR} ]; then
    LATEST_BACKUPED_UUID=$(ls -v1 ${BACKUP_DIR}uuid-*.hive | tail -n1)
  fi
  if [ "z${LATEST_BACKUPED_UUID}" != "z" ]; then
    echo -n "WARNING: The UUID of the node does not exist. The lastest backup (${LATEST_BACKUPED_UUID}) will be recovered..."
    cp -a ${LATEST_BACKUPED_UUID} ${UUID_FILE} >/dev/null 2>&1
    echo " Done"
  else
    echo -n "WARNING: The UUID of the node does not exist and no backup exist. A new one will be generated..."
    uuidgen > ${UUID_FILE}
    echo " Done"
  fi
else
  # UUID is valid only if it has been generetaed by uuidgen or if it is set to 'root' for policy server
  CHECK_UUID=`cat /opt/rudder/etc/uuid.hive | grep -E "^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}|root" | wc -l`
  # If the UUID is not valid, regenerate it
  if [ ${CHECK_UUID} -ne 1 ]; then
    echo -n "INFO: Creating a new UUID for Rudder as the existing one is invalid..."
    # Keep a backup of UUID even if it is not valid
    mkdir -p /var/backups/rudder
    cp -f /opt/rudder/etc/uuid.hive /var/backups/rudder/uuid-$(date +%Y%m%d).hive
    # Generate a new one
    uuidgen > ${UUID_FILE}
    echo " Done."
  fi
fi
}


check_and_fix_specific_rudder_agent_file() {

FILE_TO_RESTORE=$1
FILE_TYPE=$2
LATEST_BACKUPED_FILES=""

if [ ! -e ${FILE_TO_RESTORE} ]; then
  if [ -d ${BACKUP_DIR} ]; then
    LATEST_BACKUPED_FILES=$(ls -v1 ${BACKUP_DIR}rudder-agent.${FILE_TYPE}-* | tail -n1)
  fi
  if [ "z${LATEST_BACKUPED_FILES}" != "z" ]; then
    echo -n "WARNING: The file ${FILE_TO_RESTORE} does not exist. The lastest backup (${LATEST_BACKUPED_FILES}) will be recovered..."
    cp -a ${LATEST_BACKUPED_FILES} ${FILE_TO_RESTORE} >/dev/null 2>&1
    echo " Done"
  else
    echo "WARNING: The file ${FILE_TO_RESTORE} does not exist and no backup exist. Please reinstall the rudder-agent package"
  fi
fi
}


# Ensure script is executed by root
if [ ! $(whoami) = 'root' ];then echo "You must be root"; exit; fi

# Launch each check with a certain order
check_and_fix_rudder_uuid
check_and_fix_cfengine_processes
check_and_fix_specific_rudder_agent_file /etc/init.d/rudder-agent init
check_and_fix_specific_rudder_agent_file /etc/default/rudder-agent default
check_and_fix_specific_rudder_agent_file /etc/cron.d/rudder-agent cron
