#!/bin/sh
#
# This script runs a Perl script using Rudder's Perl environment if there is one

if [ -x /opt/rudder/bin/perl ]
then
  /opt/rudder/bin/perl -I /opt/rudder/lib/perl5 "$@"
else
  perl "$@"
fi
