#!/bin/sh

if [ -x /bin/uuidgen ]
then
  /bin/uuidgen

elif [ -x /usr/bin/uuidgen ]
then
  /usr/bin/uuidgen

# bare linux
elif [ -f /proc/sys/kernel/random/uuid ]
then
  cat /proc/sys/kernel/random/uuid
fi
