#!/bin/sh
set -e

CFE_DIR="/var/rudder/cfengine-community"
RUDDER_CMD="/opt/rudder/bin/rudder"
LOG_FILE="/var/log/rudder/install/rudder-agent.log"

CFRUDDER_FIRST_INSTALL="$1"
CFRUDDER_OS="$2"
CFRUDDER_USE_SYSTEMD="$3"

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL> <CFRUDDER_OS> <CFRUDDER_USE_SYSTEMD>"
  echo " This should only be called from a package preinstall command"
  exit 1
fi

echo "`date` - Starting rudder-agent pre installation script" >> ${LOG_FILE}

# Restart daemons if we stopped them, otherwise not
if [ ${CFRUDDER_FIRST_INSTALL} -ne 1 ]
then
  # Part of the package now, but create it anyway in case
  # of upgrade from a very old version
  mkdir -p /var/rudder/tmp

  if [ "${CFRUDDER_USE_SYSTEMD}" = "true" ]
  then
    if [ -f /etc/init.d/rudder-agent ]
    then
      # we are migrating from sysv to systemd
      touch /var/rudder/tmp/migration-rudder-service-systemd

      if type chkconfig > /dev/null
      then
        # If old rudder-agent service is here and enabled
        if chkconfig --list rudder-agent 2>&1 | grep -q -e 3:on -e B:on
        then
          touch /var/rudder/tmp/migration-rudder-service-enabled
        fi

        # If old rudder service is here and enabled
        if chkconfig --list rudder 2>&1 | grep -q -e 3:on -e B:on
        then
          touch /var/rudder/tmp/migration-rudder-service-enabled
        fi
      fi

      if test /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S??rudder-agent
      then
        touch /var/rudder/tmp/migration-rudder-service-enabled
      fi

      if test /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S??rudder
      then
        touch /var/rudder/tmp/migration-rudder-service-enabled
      fi

      # Test if cf-serverd is disabled
      if [ -f /etc/default/rudder-agent ]
      then
        if grep -q '^CFENGINE_COMMUNITY_RUN_1="0"' /etc/default/rudder-agent
        then
          touch /var/rudder/tmp/migration-rudder-cf-serverd-disabled
        fi
      fi
    fi
  else
    if [ -f /etc/init.d/rudder ]
    then
      # We are migrating from a pre-4.3 to 4.3
      touch /var/rudder/tmp/migration-rudder-service-rename

      # If old rudder service is here and enabled
      if type chkconfig > /dev/null
      then 
        if chkconfig --list rudder 2>&1 | grep -q -e 3:on -e B:on
        then
          touch /var/rudder/tmp/migration-rudder-service-enabled
        fi
      fi

      if test /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S??rudder
      then
        touch /var/rudder/tmp/migration-rudder-service-enabled
      fi
    fi
  fi
fi

