#!/bin/sh
set -e

CFRUDDER_FIRST_INSTALL="$1"
CFRUDDER_OS="$2"
CFRUDDER_USE_SYSTEMD="$3"
CFRUDDER_SERVER="$4"

CFE_DIR="/var/rudder/cfengine-community"
RUDDER_CMD="/opt/rudder/bin/rudder"
LOG_FILE="/var/log/rudder/install/rudder-agent-$(date +%Y%m%d%H%M%S).log"

# Closing all parents fd which are inherited, otherwise it can lead to
# a postint unable to terminate (revelant at least on debian 7)
if [ -d /proc/self/fd ]
then
  for fd in $(ls /proc/self/fd); do
    [ "${fd}" -gt 2 ] && eval "exec $fd>&-"
  done
fi

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL> <CFRUDDER_OS> <CFRUDDER_USE_SYSTEMD>"
  echo " This should only be called from a package postinstall command"
  exit 1
fi

echo "$(date) - Starting rudder-agent post installation script" >> ${LOG_FILE}

# if no conf and no server provided, try to use rudder
if [ ! -f /var/rudder/cfengine-community/policy_server.dat ] && [ "${CFRUDDER_SERVER}" = "" ]
then
  # Detect if "rudder" is a valid hostname, if so, use it as the default server
  if type getent > /dev/null 2>&1; then # glibc/linux
    if getent hosts rudder > /dev/null; then
      CFRUDDER_SERVER="rudder"
    fi
  elif type host > /dev/null 2>&1; then # aix
    if host rudder > /dev/null; then
      CFRUDDER_SERVER="rudder"
    fi
  fi
fi

# setup the policy server if we are asked to
if [ "${CFRUDDER_SERVER}" != "" ]
then
  echo "${CFRUDDER_SERVER}" > /var/rudder/cfengine-community/policy_server.dat
fi

# Do this at first install
if [ "${CFRUDDER_FIRST_INSTALL}" = "true" ]
then
  # Set rudder-agent as service
  if [ ${CFRUDDER_OS} = "aix" ]
  then
    /usr/bin/mkssys -s rudder-agent -p "${CFE_DIR}/bin/cf-execd" -a "-F" -u root -S -n15 -f9 -R
    /usr/sbin/mkitab "rudder-agent:23456789:once:/usr/bin/startsrc -s rudder-agent"
    # No need to tell init to re-read /etc/inittab, it does it automatically every 60 seconds
  elif [ ${CFRUDDER_OS} != "deb" ] && [ "${CFRUDDER_USE_SYSTEMD}" != "true" ] && [ ${CFRUDDER_OS} != "slack" ]
  then
    chkconfig --add rudder-agent
    chkconfig rudder-agent on
  elif [ "${CFRUDDER_USE_SYSTEMD}" = "true" ]
  then
    /bin/systemctl daemon-reload
    /bin/systemctl enable rudder-agent rudder-cf-execd rudder-cf-serverd
  fi
fi

# Stop the service to make sure new binaries will be run (agent check will restart it)
rudder agent stop >> ${LOG_FILE}

# Make sure the configuration is available in a standard place
ln -sf "${CFE_DIR}/policy_server.dat" "/opt/rudder/etc/policy_server.dat"

# On AIX, trigger slibclean to remove any unused library/binary object from memory
# Will prevent "Text file busy" errors during the following copy
if type slibclean > /dev/null 2>&1; then 
  slibclean >> ${LOG_FILE}
fi

# Ensure the modification date of the capability file is correct
# as it is used for cache invalidation in ncf lis-compatible-inputs
touch /opt/rudder/etc/agent-capabilities

# agent is disabled
if [ -f /opt/rudder/etc/disable-agent ]
then
  echo "********************************************************************************"
  echo "rudder-agent has been updated, but was not started as it is disabled."
  echo "To enable and start Rudder agent:"
  echo "# rudder agent enable -s"
  echo "********************************************************************************"
fi

# Try to send an inventory after upgrade to see the new agent version on the server
if [ "${CFRUDDER_FIRST_INSTALL}" != "true" ]
then
  echo "INFO: Scheduling an inventory during next run..."
  touch /opt/rudder/etc/force_inventory
fi

# Try to remove POSIX ACL if present, only during the first install
# https://issues.rudder.io/issues/8065
if [ "${CFRUDDER_FIRST_INSTALL}" = "true" ]
then
  if type setfacl > /dev/null 2>&1; then
    setfacl -R -k /var/rudder/
  fi
fi

# launch rudder agent check script, it will generate an UUID on first install or repair it if needed
# If properly configured, this will run "agent reset" which will run "agent update" which will bootstrap then update ncf with cf-agent
if command -v "setsid" >/dev/null 2>&1; then
  # detach from process group otherwise dpkg may wait forever
  setsid ${RUDDER_CMD} agent check -f >> ${LOG_FILE} 2>&1
else
  nohup ${RUDDER_CMD} agent check -f >> ${LOG_FILE} 2>&1 &
fi

echo "$(date) - Ending rudder-agent post installation script" >> ${LOG_FILE}

# force exit othewise the shell may be waiting for something
exit 0
