#!/bin/sh
set -e

CFRUDDER_FIRST_INSTALL="$1"
CFE_DIR="/var/rudder/cfengine-community"
RUDDER_CMD="/opt/rudder/bin/rudder"
LOG_FILE="/var/log/rudder/install/rudder-agent.log"
CFRUDDER_SERVER=""

# Closing all parents fd which are inherited, otherwise it can lead to
# a postint unable to terminate (revelant at least on debian 7)
for fd in $(ls /proc/self/fd); do
  [ "${fd}" -gt 2 ] && eval "exec $fd>&-"
done

if [ -z "$1" ]
then
  echo "Usage: $0 <CFRUDDER_FIRST_INSTALL>"
  echo " This should only be called from a package postinstall command"
  echo " You may want to run 'rudder agent factory-reset' instead"
  exit 1
fi

echo "`date` - Starting rudder-agent post installation script" >> ${LOG_FILE}

if [ "${CFRUDDER_SERVER}" = "" ]
then
  # Detect if "rudder" is a valid hostname, if so, use it as the default server
  if type getent > /dev/null 2>&1; then # glibc/linux
    if getent hosts rudder > /dev/null; then
      CFRUDDER_SERVER="rudder"
    fi
  elif type host > /dev/null 2>&1; then # aix
    if host rudder > /dev/null; then
      CFRUDDER_SERVER="rudder"
    fi
  fi
fi

if [ "${CFRUDDER_SERVER}" != "" ]
then
  echo "${CFRUDDER_SERVER}" > /var/rudder/cfengine-community/policy_server.dat
fi

# Reload the linker cache (to acknowledge LMDB's presence if needed)
if [ -f /etc/ld.so.conf.d/rudder.conf ]; then
  echo "Found /etc/ld.so.conf.d/rudder.conf, running ldconfig" >> ${LOG_FILE}
  ldconfig -v >> ${LOG_FILE} 2>&1
fi

# Set a "lock" to avoid CFEngine being restarted during the upgrade process
I_SET_THE_LOCK=0
if [ ! -f /opt/rudder/etc/disable-agent ]; then
  I_SET_THE_LOCK=1
  ${RUDDER_CMD} agent disable
fi

# Make sure the daemons are stopped (if the daemon exists)
[ -x "${CFE_DIR}/bin/cf-execd" ] && ${RUDDER_CMD} agent stop || true

# On AIX, trigger slibclean to remove any unused library/binary object from memory
# Will prevent "Text file busy" errors during the following copy
if type slibclean >> ${LOG_FILE} 2>&1; then 
  slibclean
fi

# Copy CFEngine binaries (Changed location from sbin/ to bin/ in version 3.4)
cp -r -f /opt/rudder/bin/cf-* ${CFE_DIR}/bin/
cp -r -f /opt/rudder/bin/rpmvercmp ${CFE_DIR}/bin/
NB_COPIED_BINARIES=`ls -1 ${CFE_DIR}/bin/ | wc -l`
if [ ${NB_COPIED_BINARIES} -gt 0 ]; then
  echo "CFEngine binaries copied to workdir" >> ${LOG_FILE}
fi

# Backup rudder-server-roles.conf
if [ -f ${CFE_DIR}/inputs/rudder-server-roles.conf ]
then
  mkdir -p /var/backups/rudder
  cp -r ${CFE_DIR}/inputs/rudder-server-roles.conf /var/backups/rudder/
  RESTORE_SERVER_ROLES_BACKUP=1
fi

# Copy initial promises if there aren't any already or,
# if the cf-promises validation fails, it means we have a broken set of promises (possibly a pre-2.8 set).
# Reset the initial promises so the server is able to send the agent a new set of correct ones.
RUDDER_UUID=`cat /opt/rudder/etc/uuid.hive 2>>${LOG_FILE} || true`
if [ ! -f ${CFE_DIR}/inputs/promises.cf ] || ! ${CFE_DIR}/bin/cf-promises >> ${LOG_FILE} 2>&1 && [ "${RUDDER_UUID}" != "root" ]
then
  mkdir -p ${CFE_DIR}/inputs
  rm -rf ${CFE_DIR}/inputs/* || true
  cp -r /opt/rudder/share/initial-promises/* ${CFE_DIR}/inputs/
  mkdir -p /var/rudder/ncf/common
  rm -rf /var/rudder/ncf/common/*
  cp -r /opt/rudder/share/initial-ncf/* /var/rudder/ncf/common/
fi

# Restore rudder-server-roles.conf if necessary
if [ "${RESTORE_SERVER_ROLES_BACKUP}" = "1" ]; then
  cp -r /var/backups/rudder/rudder-server-roles.conf ${CFE_DIR}/inputs/rudder-server-roles.conf
fi

printf "INFO: Ensuring correct permissions on the keys directory..."
# The chmod is a workaround for the limitations of rpm in rhel6 but it could be useful in other situations
chmod 700 ${CFE_DIR}/ppkeys
echo " Done."

# Create a key if we don't have one yet
if [ ! -f ${CFE_DIR}/ppkeys/localhost.priv ]
then
  printf "INFO: Creating keys for CFEngine agent..."
  ${CFE_DIR}/bin/cf-key >> ${LOG_FILE} 2>&1
  echo " Done."
fi

# Remove cfengine lock log file : http://www.rudder-project.org/redmine/issues/5488
rm -f ${CFE_DIR}/cf3.*.runlog*

# Remove the lock on CFEngine
if [ ${I_SET_THE_LOCK} -eq 1 ]; then
  ${RUDDER_CMD} agent enable
fi

# Ensure the modification date of the capability file is correct
# as it is used for cache invalidation in ncf lis-compatible-inputs
touch /opt/rudder/etc/agent-capabilities

# Restart daemons if we stopped them, otherwise not
if [ ${CFRUDDER_FIRST_INSTALL} -ne 1 ]
then
  # Check if agent is disabled
  if [ ! -f /opt/rudder/etc/disable-agent ]
  then
    if [ -r ${CFE_DIR}/inputs/failsafe.cf -o -r ${CFE_DIR}/inputs/promises.cf ]
    then
      ${RUDDER_CMD} agent start || true
    fi
  else
    echo "********************************************************************************"
    echo "rudder-agent has been updated, but was not started as it is disabled."
    echo "To enable and start Rudder agent:"
    echo "# rudder agent enable -s"
    echo "********************************************************************************"
  fi
elif [ "${RUDDER_UUID}" != "root" ]
then
  echo "********************************************************************************"
  echo "rudder-agent has been installed (not started). This host can be a Rudder node."
  echo "To get started, configure your Rudder server's hostname and launch the agent:"
  echo "# echo 'rudder.server' > ${CFE_DIR}/policy_server.dat"
  echo "# rudder agent start"
  echo "This node will then appear in the Rudder web interface under 'Accept new nodes'."
  echo "********************************************************************************"
fi

# Add a default agent cron at first install
if [ ${CFRUDDER_FIRST_INSTALL} -eq 1 ]
then
  if [ `uname -s` != 'AIX' ]
  then
    echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * root ${RUDDER_CMD} agent check > /dev/null" > /etc/cron.d/rudder-agent
    chmod 644 /etc/cron.d/rudder-agent
  fi
fi

# Try to send an inventory after upgrade to see the new agent version on the server
if [ ${CFRUDDER_FIRST_INSTALL} -ne 1 ]
then
  echo "INFO: Scheduling an inventory during next run..."
  touch /opt/rudder/etc/force_inventory
fi

# Try to remove POSIX ACL if present, only during the first install
# http://www.rudder-project.org/redmine/issues/8065
if [ ${CFRUDDER_FIRST_INSTALL} -eq 1 ]
then
  if type setfacl >> ${LOG_FILE} 2>&1; then
    setfacl -R -k /var/rudder/
  fi
fi

# launch rudder agent check script, it will generate an UUID on first install or repair it if needed
nohup ${RUDDER_CMD} agent check -f >> ${LOG_FILE} 2>&1 &

