#!/bin/sh
#####################################################################################
# Copyright 2015 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

# Manage rudder nodes key directly in LDAP

set -e

usage() {
  echo "Usage:"
  echo "  $0 reset-status <node_uuid>"
  echo "  $0 change-key <node_uuid> <public_key_file>"
  exit 1
}

ACTION="$1"
UUID="$2"
PUBKEY="$3"
RUDDER_OPT="/opt/rudder"
ACCEPTED_NODES_BASE="ou=Nodes,ou=Accepted Inventories,ou=Inventories,cn=rudder-configuration"

if [ "${ACTION}" = "reset-status" ]
then
  [ -z "${UUID}" ] && usage
elif [ "${ACTION}" = "change-key" ]
then
  [ -z "${UUID}" ] && usage
  [ -z "${PUBKEY}" ] && usage
else
  usage
fi

# Get how many access credentials we got for LDAP in /opt/rudder/etc/rudder-web.properties
# (should have 2, user and password)
LDAP_CREDENTIALS=$(grep -c -E "^ldap.auth(dn|pw)[ \t]*=" /opt/rudder/etc/rudder-web.properties || true)

if [ -f /opt/rudder/etc/rudder-web.properties -a ${LDAP_CREDENTIALS} -eq 2 ]; then
  # Get the database access credentials from the rudder-web.properties file
  LDAP_USER="$(grep -E '^ldap.authdn[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
  LDAP_PASSWORD="$(grep -E '^ldap.authpw[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d "=" -f 2-)"
  LDAP_SERVER="$(grep -E '^ldap.host[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2-)"
  LDAP_PORT="$(grep -E '^ldap.port[ \t]*=' ${RUDDER_OPT}/etc/rudder-web.properties | cut -d '=' -f 2-)"

else
  # No database access credentials in rudder-web.properties
  echo "ERROR: Database access credentials are missing in /opt/rudder/etc/rudder-web.properties."
  exit 1
fi

# Commands
LDAP_PARAMETERS="-H ldap://${LDAP_SERVER}:${LDAP_PORT}/ -D ${LDAP_USER} -w ${LDAP_PASSWORD} -x"


if [ "${ACTION}" = "reset-status" ]
then

  ldapmodify ${LDAP_PARAMETERS} <<EOF
dn: nodeId=${UUID},${ACCEPTED_NODES_BASE}
changetype: modify
delete: keyStatus

EOF

elif [ "${ACTION}" = "change-key" ]
then

  if [ ! -s "${PUBKEY}" ]
  then
    echo "ERORR ${PUBKEY} file does not exist or is empty"
    exit 2
  fi

  PUBKEY=$(readlink -f "${PUBKEY}")

  # extract and excape key public key (double escape because it will be used in a perl regex replacement
  pub_key_content=$(perl -pe 's/\n/\\\\n/g' "${PUBKEY}" | perl -pe 's|/|\\/|g')
  # extract agentName attribute from ldap into a file
  current_agentname_file=$(ldapsearch ${LDAP_PARAMETERS} -tt -b "${ACCEPTED_NODES_BASE}" "nodeId=${UUID}" agentName | grep agentName: | perl -pe 's|agentName:< file://(.*)|$1|')
  # extract securityToken value from agentName in JSON and replace public key (again escaped for next use)
  new_token=$(perl -pe 's/.*"securityToken":\{(.*?)\}.*/$1/' "${current_agentname_file}" | perl -pe 's/(.*)"value":".*?"(.*)/$1"value":"'"${pub_key_content}"'"$2/' | perl -pe 's|([/\\])|\\$1|g')
  # put securityToken value back into JSON
  perl -i -pe 's/(.*"securityToken":\{).*?(\}.*)/$1'"${new_token}"'$2/' "${current_agentname_file}"
  # Put the new json value into ldap attribute agentName
  ldapmodify ${LDAP_PARAMETERS} <<EOF
dn: nodeId=${UUID},${ACCEPTED_NODES_BASE}
changetype: modify
replace: agentName
agentName:< file://${current_agentname_file}

EOF
  rm "${current_agentname_file}"
fi
