#!/bin/sh

set -e

#####################################################################################
# Copyright 2011 Normation SAS
#####################################################################################
#
# This file is part of Rudder.
# 
# Rudder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# In accordance with the terms of section 7 (7. Additional Terms.) of
# the GNU General Public License version 3, the copyright holders add
# the following Additional permissions:
# Notwithstanding to the terms of section 5 (5. Conveying Modified Source
# Versions) and 6 (6. Conveying Non-Source Forms.) of the GNU General
# Public License version 3, when you create a Related Module, this
# Related Module is not considered as a part of the work and may be
# distributed under the license agreement of your choice.
# A "Related Module" means a set of sources files including their
# documentation that, without modification of the Source Code, enables
# supplementary functions or services in addition to those offered by
# the Software.
# 
# Rudder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Rudder.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

#
# This script is intended to change the host name of the
# Rudder root server in Rudder's LDAP database.
#
ECHO=/bin/echo

usage() {
	${ECHO} "Usage: $0 <new hostname for Rudder root server>"
}

# Get the LDAP access credentials
RELAY_NEW_HOSTNAME=$1
LDAP_EXISTS=$(/opt/rudder/sbin/slapcat 2>/dev/null | grep "rudder-configuration" | wc -l)
LDAP_CREDENTIALS=`grep -E "^ldap.(authdn|authpw)=" /opt/rudder/etc/rudder-web.properties | wc -l`
if [ -f /opt/rudder/etc/rudder-web.properties -a ${LDAP_CREDENTIALS} -eq 2 ]; then
        LDAP_USER=$(grep -E "^ldap.authdn=" /opt/rudder/etc/rudder-web.properties |cut -d "=" -f 2-)
        LDAP_PASSWORD=$(grep -E "^ldap.authpw=" /opt/rudder/etc/rudder-web.properties |cut -d "=" -f 2-)
else
        ${ECHO} "WARNING: LDAP properties are missing in /opt/rudder/etc/rudder-web.properties"
        if [ -f /opt/rudder/etc/openldap/slapd.conf ]; then
                LDAP_USER=$(grep "^rootdn" /opt/rudder/etc/openldap/slapd.conf | sed "s/\w*\s*['\"]\?\([^\"']*\)['\"]\?$/\1/")
                LDAP_PASSWORD=$(grep "^rootpw" /opt/rudder/etc/openldap/slapd.conf | sed "s/\w*\s*['\"]\?\([^\"']*\)['\"]\?$/\1/")
        else
                ${ECHO} "ERROR: /opt/rudder/etc/openldap/slapd.conf doesn't exist"
                exit 1
        fi
fi

# Check arguments
if [ "${RELAY_NEW_HOSTNAME}" = "" ]; then
	${ECHO} "ERROR: Need the new host name of the Root server as an argument, aborting."
	usage
	exit 1
elif [ "${RELAY_NEW_HOSTNAME}" = "new-root.example.org" ]; then
	${ECHO} "ERROR: Please use a real host name, not the one supplied in the documentation, aborting."
	exit 1
fi

${ECHO} -e "Rudder root server host name change script starting, using host name ${RELAY_NEW_HOSTNAME}.\n"

#######################################################################################################################
## Changing the root server host name
#######################################################################################################################

${ECHO} -n "INFO: Changing the root server host name..."
/opt/rudder/bin/ldapmodify -H ldap://localhost -x -D "${LDAP_USER}" -w ${LDAP_PASSWORD} <<EOF >/dev/null 2>&1 || echo -n " modification failed."
dn: nodeId=root,ou=Nodes Configuration,ou=Rudder,cn=rudder-configuration
changetype: modify
replace: nodeHostname
nodeHostname: ${RELAY_NEW_HOSTNAME}
-
replace: targetNodeHostname
targetNodeHostname: ${RELAY_NEW_HOSTNAME}
EOF
${ECHO} " Done."

#######################################################################################################################
# As the server name was changed, we force the root server to run a new inventory on the next CFEngine run.
#######################################################################################################################
${ECHO} -n "INFO: Scheduling a new inventory collection on the root server now..."
touch /opt/rudder/etc/force_inventory
${ECHO} " Done."

${ECHO} -e "\nSuccess: all steps completed successfully."
