#!/bin/sh

set -e

# TODO
CFRUDDER_FIRST_INSTALL="true"
CFRUDDER_USE_SYSTEMD="false"
server=""
/opt/rudder/share/package-scripts/rudder-agent-postinst "${CFRUDDER_FIRST_INSTALL}" "osx" "${CFRUDDER_USE_SYSTEMD}" "${server}"


exit 0
