#!/bin/sh

# Configure maxsize and sockbuf_max_incoming_auth in /opt/rudder/etc/openldap/slapd.conf based on
# content of /etc/default/rudder-slapd, or auto-computed based on available memory

# Script specific
PROG_NAME='rudder-slapd'
OS=`uname -s`   # To adapt message printing
SLAPD_CONF_FILE=/opt/rudder/etc/openldap/slapd.conf


#====================================================================
# Message function
#====================================================================
message() {
  # $1: syslog level
  # $2: message

  if [ $OS = "Linux" ]
  then
    logger -p "local4.$1" -s -t $PROG_NAME -i "$2"
  else
    # Try without option -s
    logger -p "local4.$1" -t $PROG_NAME -i "$2"
    echo "$PROG_NAME: $2"
  fi
}

#====================================================================



#====================================================================
# Load specific parameters
#====================================================================
. /opt/rudder/etc/rudder-slapd.conf

if [ -f /etc/default/$PROG_NAME ]
then
  . /etc/default/$PROG_NAME
  message "info" "[INFO] Using /etc/default/$PROG_NAME for configuration"
fi

# configuration of mdbsize
if [ "${RUDDER_MDBSIZE}" != "noauto" ]
then
  if [ "${RUDDER_MDBSIZE}" = "auto" ] || [ "${RUDDER_MDBSIZE}" = "" ]
  then
    # 100GB as max DB size on 64bits should be enough
    MDBSIZE=107374182400
  else
    # set cache size to the value provided
    MDBSIZE=${RUDDER_MDBSIZE}
  fi
  sed -i '/^[ \t]*maxsize/d' ${SLAPD_CONF_FILE}
  sed -i 's/^\([ \t]*suffix[ \t]\+"cn=rudder-configuration".*\)/\1\nmaxsize '${MDBSIZE}'/' ${SLAPD_CONF_FILE}
fi

# Remove reference to hdb backend
sed -i "/moduleload.*back_hdb.la/d" /opt/rudder/etc/openldap/slapd.conf

if [ "${RUDDER_MAX_INCOMING_AUTH}" != "" ]
then
    # Set value to the one in etc/default
    MAX_INCOMING_AUTH=${RUDDER_MAX_INCOMING_AUTH}
else
    # 1000000000 as default max size fo incoming query
    MAX_INCOMING_AUTH=1000000000
fi
sed -i '/^[ \t]*sockbuf_max_incoming_auth/d' ${SLAPD_CONF_FILE}
sed -i 's/^\([ \t]*argsfile[ \t]\+\/.*\)/\1\nsockbuf_max_incoming_auth '${MAX_INCOMING_AUTH}'/' ${SLAPD_CONF_FILE}

