#!/bin/bash

set -x


pom_file="$1"
namespace="$2"
name="$3"
outfile="$4"
if [ ! -f "${pom_file}" ] || [ "${namespace}" = "" ] || [ "${name}" = "" ] || [ "${outfile}" = "" ]
then
  echo "Usage $0 <pom_file> <artifact_namespace> <artifact_name> <outfile>"
  exit 1
fi

RELEASE_BASE_URL="https://repository.rudder.io/maven/releases"
SNAPSHOT_BASE_URL="https://repository.rudder.io/maven/snapshots"

mvn_version=$(sed -n '/<parent>/,/<.parent>/s/.*<version>\(.*\)<.version>.*/\1/p' "${pom_file}")
namespace_url=$(echo "${namespace}" | tr '.' '/')

if [[ "${mvn_version}" =~ SNAPSHOT ]]
then
  snap_version=$(curl -s ${SNAPSHOT_BASE_URL}/${namespace_url}/${name}/${mvn_version}/maven-metadata.xml | sed -n '/<snapshot>/,/<.snapshot>/p' | tr -d '\n' | sed 's/.*<timestamp>\(.*\)<.timestamp>.*<buildNumber>\(.*\)<.buildNumber>.*/\1-\2/')
  url=${SNAPSHOT_BASE_URL}/${namespace_url}/${name}/${mvn_version}/${name}-${mvn_version/SNAPSHOT/$snap_version}.war
else
  url=${RELEASE_BASE_URL}/${namespace_url}/${name}/${mvn_version}/${name}-${mvn_version}.war
fi
curl -s -o "${outfile}" "${url}"

# Set a minimum size of 1Mb
minimumsize=1000000
actualsize=$(wc -c <"${outfile}")
if [ ${actualsize} -le ${minimumsize} ]; then
    echo "${outfile} size is less than 1Mb, abort build"
    exit 1
fi
