#!/usr/bin/python
# cc(1) wrapper to build CPAN Perl modules with GCC on OpenSolaris. -mrb
import os, sys, re
path = '/usr/bin/gcc'
args = []
i = 0
while i < len(sys.argv):
       if i == 0:
               args.append(path)
       else:
           m = re.match(r'^-xO(\d)$', sys.argv[i])
           if m:
               args.append('-O'+m.group(1))
           elif sys.argv[i] == '-KPIC':
                   args.append('-fPIC')
           elif sys.argv[i] == '-xspace':
                   pass
           elif sys.argv[i] == '-xildoff':
                   pass
           else:
                   args.append(sys.argv[i])
       i += 1
print("Diverting cc to '" + path + " " + " ".join(args) + "'")
os.execv(path, args)
